name: togo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  sqflite: 2.0.2
  flutter_cupertino_date_picker: 1.0.26+2
  intl: 0.17.0
  file_picker: 4.5.0
  fluttertoast: 8.0.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

